# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170729_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='short_text',
        ),
    ]
