# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170729_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='front_page',
            field=models.BooleanField(default=False),
        ),
    ]
